# Generated by Django 4.2.4 on 2023-08-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sorov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish', models.CharField(max_length=500)),
                ('idpassport', models.CharField(max_length=500)),
                ('Yashashmanzili', models.CharField(max_length=500)),
                ('mfynomi', models.CharField(max_length=500)),
                ('kochanomi', models.CharField(max_length=500)),
                ('telefonraqami', models.CharField(max_length=500)),
                ('rasmvavidio', models.FileField(upload_to='')),
                ('matn', models.TextField()),
            ],
        ),
    ]
